### ISSUE TITLE
Non PaymentUI payment flow

### ISSUE THREAD

**Issue by diayan** [PaystackHQ/paystack-sdk-ios#115]
I am trying to use this sdk in my app for payment but I don't want to use the PaymentUI payment flow (ie: I don't want to use Paystack's payment UI). I noticed there's no documentation about that. Is there a different sdk to achieve that?

**Comment by Peter-John-paystack** [comment]
Hi @diayan . Sorry for the delay in response. 

This new Mobile SDK for iOS is made in a way that you do need to use the PaymentUI. We currently don't have a way for you to use this SDK without the PaymentUI. This is intentional since we want everyone to have a consistent experience when using our Mobile SDK and customers know when they see the Paystack UI they can trust their payment is secure. 

However you can also use our API's if you would like to, but this will involves calling the Paystack endpoints from your backend and calling your own backend. (For some endpoints you do need to be PCI compliant to use them)

Please see [documentation](https://paystack.com/docs/api/) for that. Let me know if this helps.
